### ISSUE TITLE
[Schema Inaccuracy] Incorrect operationId

### ISSUE THREAD

**Issue by rachmari** [github/rest-api-description#119]
# Schema Inaccuracy

Originally reported by @gr2m in https://github.com/github/openapi/issues/340:

https://github.com/github/openapi/blob/fdd3f34435dc90c0db37126c795bc74f4076d820/definitions/operations/repos/update-status-check-potection.yml#L12

This should be `repos/update-status-check-protection`

```diff
- repos/update-status-check-potection
+ repos/update-status-check-protection
```

I'd be happy to send a pull request but I see the operationID show up in many files, and I'm not sure which need to be changed and which get updated automagically.

Also this needs a new entry in `x-githubBreakingChanges:`

```yml
  - type: operation
    date: '2020-07-29'
    note: '"repos/update-status-check-potection" operation ID is now "repos/update-status-check-protection"'
    before:
      operationId: repos/update-status-check-potection
    after:
      operationId: repos/update-status-check-protection
```

And the existing entry should be update, because it does actually not have the typo

```diff
  - type: operation
    date: '2020-06-04'
-   note: '"repos/update-protected-branch-required-status-checks" operation ID is now "repos/update-status-checks-protection"'
+   note: '"repos/update-protected-branch-required-status-checks" operation ID is now "repos/update-status-checks-potection"'
    before:
      operationId: repos/update-protected-branch-required-status-checks
    after:
-     operationId: repos/update-status-checks-protection
+     operationId: repos/update-status-checks-potection
```
