### ISSUE TITLE
[Schema Inaccuracy] confusing installation account type

### ISSUE THREAD

**Issue by yanyongyu** [github/rest-api-description#1417]
# Schema Inaccuracy

Current 3.1 description installation account schema uses both type and anyof. Should this uses anyof only? (like what 3.0 do)

```yaml
installation:
  title: Installation
  description: Installation
  type: object
  properties:
    account:
      anyOf:
      - "$ref": "#/components/schemas/simple-user"
      - "$ref": "#/components/schemas/enterprise"
      type:
      - 'null'
      - object
```

## Expected

```yaml
installation:
  title: Installation
  description: Installation
  type: object
  properties:
    account:
      anyOf:
      - "$ref": "#/components/schemas/simple-user"
      - "$ref": "#/components/schemas/enterprise"
      - type: 'null'
```
