### ISSUE TITLE
[Schema Inaccuracy] Request field new_owner of repository transfer endpoint not marked as required

### ISSUE THREAD

**Issue by pluehne** [github/rest-api-description#155]
# Schema Inaccuracy

The `repos/transfer` operation for transferring repositories has a `new_owner` property in its request body to designate the new owner of the repository:

```yaml
new_owner:
  type: string
  description: "**Required:** The username or organization name the
    repository will be transferred to."
```

As the documentation states, this field is required (which makes sense). However, this is not reflected by the specification, as the request body object doesn’t declare any fields to be required.

## Expected

I’d expect the `requestBody` schema to include

```yaml
required:
- new_owner
```
