### ISSUE TITLE
[Schema Inaccuracy] Issue `body_html` maybe `null`

### ISSUE THREAD

**Issue by yanyongyu** [github/rest-api-description#1639]
# Schema Inaccuracy

As the `body` field of the `Issue` object schema, the issue body may be empty (`null`):

```yaml
body:
  description: Contents of the issue
  type:
  - string
  - 'null'
  examples:
  - It looks like the new widget form is broken on Safari. When I try and
    create the widget, Safari crashes. This is reproducible on 10.8, but not
    10.9. Maybe a browser bug?
```

but the `body_html` and `body_text` field cannot be `null` in the schema. I tried to get some issue without body. The `body_html` and `body_text` of the issue is also `null`.

## Expected

The `body_html` and `body_text` field in the `Issue` schema should be string or null.

## Reproduction Steps

curl -H "Accept: application/vnd.github.full+json" https://api.github.com/repos/nonebot/nonebot2/issues/1305
