### ISSUE TITLE
Possibly incorrect type for visibility field in repository schemas

### ISSUE THREAD

**Issue by mariusknaust** [github/rest-api-description#164]
The `visibility` field from the `nebula` preview in `/components/schemas/{repository, team-repository, full-repository}` is listed as a plain string unlike the other occurrences of the `visibility` field where it is listed as a string enum. This is probably an error, as the description states the enum values.

```
visibility:
          description: 'The repository visibility: public, private, or internal.'
          type: string
          example: public
```
