### ISSUE TITLE
[Schema Inaccuracy] Pull Request Simple `head.repo` object may be `null`

### ISSUE THREAD

**Issue by yanyongyu** [github/rest-api-description#1811]
# Schema Inaccuracy

The `Pull Request Simple` object field `head.repo` may be null if user has deleted the repo, as the `Pull Request` object.

```yaml
schemas:
  # incorrect
  pull-request-simple:
    type: object
    title: Pull Request Simple
    properties:
      head:
        type: object
        properties:
          repo:
            "$ref": "#/components/schemas/repository"

  # correct
  pull-request:
    type: object
    title: Pull Request
    properties:
      ...
      head:
        type: object
        properties:
          repo:
            type:
            - object
            - 'null'
```

## Expected

change the repo field to oneof `repository` / `type: null`

## Reproduction Steps

list pull request using `curl -X GET https://api.github.com/repos/apache/pulsar/pulls?state=open`

get pull request https://github.com/apache/pulsar/pull/6036 which head repo was deleted
