### ISSUE TITLE
[Schema Inaccuracy] Pull Request Simple `labels.items.properties.description` may be `null`

### ISSUE THREAD

**Issue by yanyongyu** [github/rest-api-description#1812]
# Schema Inaccuracy

The `Pull Request Simple` object field `labels.items.properties.description` may be null, as the `Pull Request` object.

```yaml
schemas:
  # incorrect
  pull-request-simple:
    type: object
    title: Pull Request Simple
    properties:
      labels:
      type: array
      items:
        properties:
          description:
            type: string

  # correct
  pull-request:
    type: object
    title: Pull Request
    properties:
      labels:
      type: array
      items:
        properties:
          description:
            type:
            - string
            - 'null'
```

## Expected

change the repo field to oneof `repository` / `type: null`

## Reproduction Steps

list pull request using `curl -X GET https://api.github.com/repos/apache/pulsar/pulls?state=open`

Related to https://github.com/yanyongyu/githubkit/issues/7
