### ISSUE TITLE
[Schema Inaccuracy] Not all datetimes are defined as such

### ISSUE THREAD

**Issue by pimterry** [github/rest-api-description#198]
# Schema Inaccuracy

OpenAPI allows defining string formats, including `date-time`. This is used in some places in this spec, but not always. Some dates are listed just as free-text strings.

## Expected

It would be useful if date time values (parameters especially, for validation) were defined as such.

## Reproduction Steps

Some examples:

`#/components/since`:

```yaml
      name: since
      description: 'Only show notifications updated after the given time. This is
        a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
        `YYYY-MM-DDTHH:MM:SSZ`.'
      in: query
      required: false
      schema:
        type: string
        # should be "format: date-time" here I think
```

`#/paths/"/repos/{owner}/{repo}/commits"/get/parameters`:

```yaml
      - name: until
        description: 'Only commits before this date will be returned. This is a timestamp
          in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.'
        in: query
        required: false
        schema:
          type: string
          # should be "format: date-time" here too
```

There's quite a few examples of this, they're easy to find if you search for "8601" or "YYYY-MM-DD"
