### ISSUE TITLE
[Schema Inaccuracy] "GET /repos/{owner}/{repo}/issues" - incorrect schema for milestone parameter

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#226]
Follow up to https://github.com/WordPress/gutenberg/pull/29043#discussion_r588545998 /cc @ockham

# Schema Inaccuracy

```yml
      - name: milestone
        description: If an `integer` is passed, it should refer to a milestone by
          its `number` field. If the string `*` is passed, issues with any milestone
          are accepted. If the string `none` is passed, issues without milestones
          are returned.
        in: query
        required: false
        schema:
          type: string
```

## Expected

The description says that the `milestone` parameter can also be a number

> If an `integer` is passed, it should refer to a milestone by its `number` field. If the string `*` is passed, issues with any milestone are accepted. If the string `none` is passed, issues without milestones are returned.

## Reproduction Steps

n/a
