### ISSUE TITLE
[Schema Inaccuracy] Security Schemes Missing

### ISSUE THREAD

**Issue by philsturgeon** [github/rest-api-description#237]
# Schema Inaccuracy

GitHub REST API uses OAuth2 access tokens, and has some support for query string tokens (deprecated) and basic auth (hmmmm) which could be described in your OpenAPI.

- [GitHub REST API: Authentication](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#authentication)
- [Swagger.io Authentication Tutorial](https://swagger.io/docs/specification/authentication/)
- [Avoid figuring out YAML syntax for security schemas with Stoplight Studio](https://meta.stoplight.io/docs/studio/docs/Design-and-Modeling/10-api-security.md)

## Expected

```
    components:
      securitySchemes:
        BasicAuth:
          type: http
          scheme: basic

        OAuth2:
          type: oauth2
          flows:
            authorizationCode:
              authorizationUrl: https://example.com/oauth/authorize
              tokenUrl: https://example.com/oauth/token
              scopes:
                read: Grants read access
                write: Grants write access
                admin: Grants access to admin operations
```

_Also this gave me the idea to make security schemes in OpenAPI, deprecateable thank you! https://github.com/OAI/OpenAPI-Specification/issues/2506_
