### ISSUE TITLE
[Schema Inaccuracy] `token` parameter for `POST /orgs/{org}/packages/{package_type}/{package_name}/restore`

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#245]
# Schema Inaccuracy

I didn't test this myself, it's just an assumption

The current schema is

```yml
  "/orgs/{org}/packages/{package_type}/{package_name}/restore":
    post:
      summary: Restore a package for an organization
      description: |-
        Restores an entire package in an organization.

        You can restore a deleted package under the following conditions:
          - The package was deleted within the last 30 days.
          - The same package namespace and version is still available and not reused for a new package. If the same package namespace is not available, you will not be able to restore your package. In this scenario, to restore the deleted package, you must delete the new package that uses the deleted package's namespace first.

        To use this endpoint, you must have admin permissions in the organization and authenticate using an access token with the `packages:read` and `packages:write` scope. In addition:
        - If `package_type` is not `container`, your token must also include the `repo` scope.
        - If `package_type` is `container`, you must also have admin permissions to the container that you want to restore.
      tags:
      - packages
      operationId: packages/restore-package-for-org
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/packages#restore-a-package-for-an-organization
      parameters:
      - "$ref": "#/components/parameters/package_type"
      - "$ref": "#/components/parameters/package_name"
      - "$ref": "#/components/parameters/org"
      - name: token
        description: package token
        schema:
          type: string
        required: false
        in: query
```

Is the `token` really passed as a query parameter? Or is it passed as part of the request body?
