### ISSUE TITLE
[Schema Inaccuracy] `create-release` api param `make_latest` default value error

### ISSUE THREAD

**Issue by yanyongyu** [github/rest-api-description#2496]
# Schema Inaccuracy

Docs: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
Schema:

```yaml
make_latest:
  type: string
  enum:
  - 'true'
  - 'false'
  - legacy
  default: true
```

default value of `make_latest` is a boolean value (not quoted).

## Expected

```yaml
make_latest:
  type: string
  enum:
  - 'true'
  - 'false'
  - legacy
  default: 'true'
```

## Reproduction Steps

pass
