### ISSUE TITLE
[Schema Inaccuracy] `merge-group` schema `description` property isn't a valid OSA string

### ISSUE THREAD

**Issue by WyriHaximus** [github/rest-api-description#2609]
# Schema Inaccuracy

```yaml
   merge-group:
      type: object
      title: Merge Group
      description: 'A group of pull requests that the merge queue has grouped together
        to be merged.

'
```

## Expected

```yaml
    merge-group:
      type: object
      title: Merge Group
      description: 'A group of pull requests that the merge queue has grouped together to be merged.'
```

The PHP parser I'm using for this throws an exception when trying to parse it:

```
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Malformed inline YAML string at line 82925. in /__w/github-root/github-root/vendor/symfony/yaml/Parser.php:1152
```

This is currently present in the [`GitHub`](https://github.com/php-api-clients/github-root/actions/runs/5254762623/jobs/9493779541#step:12:11) and [`GitHubEnterpriseCloud`](https://github.com/php-api-clients/github-root/actions/runs/5243637601/jobs/9468578792#step:12:11)
