### ISSUE TITLE
[Request] Support for Authentication in the .yaml file

### ISSUE THREAD

**Issue by jefeish** [github/rest-api-description#2734]
### Description:

I have been using the [Swagger UI](https://swagger.io/tools/swagger-ui/) with [GitHub pages](https://jefeish.github.io/swagger-pages/) to display the GitHub REST API,  but I do not see `Authorize` support in the UI.

I added the following `Authorize` option (according to the Swagger UI - [Bearer Authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/) docs)

    
```yaml
security:
  - bearerAuth: [] 
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
```

---

This enables the `Authorize` option and makes it easier for our customers to test the API in Swagger.

<img width="974" alt="Screenshot 2023-07-12 at 19 23 44" src="https://github.com/github/rest-api-description/assets/863198/1c32ccaf-0ae6-4e85-ba46-c9a3385d64d2">

---

Would it be possible to add this ?

Thx
