### ISSUE TITLE
[Schema Inaccuracy] Undocumented "Pending" State for a Check Suite 

### ISSUE THREAD

**Issue by Avenel** [github/rest-api-description#3095]
# Schema Inaccuracy

Hello,

This inaccuracy is about a missing state of a Check Suite which is not included in the schema (for reference: [Check Suite API Documentation](https://docs.github.com/en/rest/checks/suites?apiVersion=2022-11-28#get-a-check-suite)). The documented states for Check Suite API response are "queued", "in_progress", and "completed". However, I have encountered an additional state, namely "pending".

In addition I have seen this state (and some more) in the GraphQL API documentation for a [CheckSuiteState Enum](https://docs.github.com/en/graphql/reference/enums#checkstatusstate). 

## Expected

The state pending and the other missing states documented in the [CheckState Enum](https://docs.github.com/en/graphql/reference/enums#checkstatusstate) are in the schema for _all_ occurrences (e.g., in the REST API call for getting a list of all Check Suites) of the property _status_ of a Check Suite.

## Reproduction Steps

This "pending" state can be induced by implementing a concurrency within a workflow. This action prevents the same workflow from being executed simultaneously. Here's an example of how this might be set up in YAML:

```
name: Do something

on:
  push:
    branches:
    - main
    
concurrency: test

jobs:
  one:
    runs-on: ubuntu-latest
    name: Do it
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Wait
      run: |
        sleep 120
```

When this workflow is triggered twice, the API response includes the "pending" state:

```
{
  "id": 9170123123,
  "node_id": "CS_kwSOJbvS3c8AAAADsy2zEw",
  "head_branch": "main",
  "head_sha": "3bcc59988530adbb6e031f1b526a763e7418d920",
  "status": "pending",
  "conclusion": null,
  "url": "https://api.github.com/repos/my-test-repo/wf-test/check-suites/15291018543",
  ...
  "pull_requests": [],
  "app": {
    "id": 15238,
    "slug": "github-actions",
    ...
  }
}

```

Thank you in advance for looking into this.

Best Regards.
