### ISSUE TITLE
[Schema Inaccuracy] Invalid examples reported by Spectral

### ISSUE THREAD

**Issue by philsturgeon** [github/rest-api-description#31]
# Schema Inaccuracy

I know you lot use [Spectral](https://stoplight.io/open-source/spectral/) for some internal stuff, and I wanted to let you know we've been working on a new feature that lets you know when examples are invalid against their defined schema (https://github.com/stoplightio/spectral/pull/1284). It looks like there's quite a few invalid examples in this repo, so I figured I should give you a heads up to resolve them before you upgrade and have to fix things in a rush.

## Expected

I'd expect none of these errors to be here. (Some are showing up twice and we're investigating why, and some of the errors are a little hard to read and we're working on that too).

<img width="1112" alt="Screen Shot 2020-08-21 at 5 10 31 PM" src="https://user-images.githubusercontent.com/67381/90906633-40eafa00-e3d2-11ea-91a8-00fee058aa95.png">

It's because the enum is only showing `uploaded`, and then the example is `open`. 

```yaml
        state:
          description: State of the release asset.
          type: string
          enum:
          - uploaded
          example: open
```

I'd ditch that example and put it in the enum. Most tooling will take an enum value and use it as an example if a property doesn't have one (especially ReDoc, which you mentioned in the README.md).

```yaml
        state:
          description: State of the release asset.
          type: string
          enum:
          - uploaded
          - open
```

Simple enough fix right?

## Reproduction Steps

Clone [spectral](https://github.com/stoplightio/spectral/).

```bash
$ gco fix/support-examples-validation
$ yarn
$ yarn build
$ yarn cli lint {path-to-this-repo}/descriptions/api.github.com/api.github.com.yaml
```
