### ISSUE TITLE
[Schema Inaccuracy] package-version.metadata.docker.properties.tag

### ISSUE THREAD

**Issue by er1c** [github/rest-api-description#337]
# Schema Inaccuracy

```
            docker:
              type: object
              title: Docker Metadata
              properties:
                tag:
                  type: array
              required:
              - tags
```

The properties should be `tags` not `tag`, or the required should be changed to `tag`
