### ISSUE TITLE
[Schema Inaccuracy] List organization repositories sorting

### ISSUE THREAD

**Issue by dmmatson** [github/rest-api-description#3445]
# Schema Inaccuracy

List organization repositories
`get "/organizations/:organization_id/repos"`

## Expected

There are two issues with this description...

1.
```
      description: The property to sort the results by.
        in: query
        required: false
        schema:
          type: string
          enum:
          - created
          - updated
          - pushed
          - full_name
          default: created
```

We also support sorting by `name`.  [[code](https://github.com/github/github/blob/a9c397b9417232e8b0575faa4d64ee882cbe9ba1/packages/repositories/app/models/repository.rb#L313)]

2.
```
    - name: direction
        description: 'The order to sort by. Default: `asc` when using `full_name`,
          otherwise `desc`.'
        in: query
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
```

The fields that sort in ASC order are `full_name`, `id`, and `name`. [[code](https://github.com/github/github/blob/a9c397b9417232e8b0575faa4d64ee882cbe9ba1/packages/repositories/app/models/repository.rb#L285)]

## Reproduction Steps

`GH_DEBUG=1 gh api -X GET --jq ".[].name" "https://api.github.com/orgs/github/repos?sort=name&per_page=100"`
