### ISSUE TITLE
Webhooks descriptions have the summary and description reversed

### ISSUE THREAD

**Issue by lornajane** [github/rest-api-description#3858]
# Schema Inaccuracy

Looking at the "next" (OpenAPI 3.1) version of the OpenAPI description, I think the `description` and `summary` fields have had their content reversed.
 - Summary should be a short summary to display in a list
 - Description can be longer, and supports Markdown.

## Expected

```yaml
webhooks:
  branch-protection-configuration-disabled:
    post:
      operationId: branch-protection-configuration/disabled
      summary: All branch protections were disabled for a repository.
      description: |-
        This event occurs when there is a change to branch protection configurations for a repository.
        For more information, see "[About protected branches](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)."
        For information about using the APIs to manage branch protection rules, see "[Branch protection rule](https://docs.github.com/graphql/reference/objects#branchprotectionrule)" in the GraphQL documentation or "[Branch protection](https://docs.github.com/rest/branches/branch-protection)" in the REST API documentation.

        To subscribe to this event, a GitHub App must have at least read-level access for the "Administration" repository permission.
```

## Reproduction Steps

Look at the API description
