### ISSUE TITLE
[Schema Inaccuracy] "Content Tree" `encoding` is a required property, but is unlisted

### ISSUE THREAD

**Issue by thejcannon** [github/rest-api-description#3860]
# Schema Inaccuracy

The "Content Tree" object lists `encoding` as a required property, but doesn't list the `encoding` property itself.

```
    content-tree:
      title: Content Tree
      description: Content Tree
      type: object
      (fields omitted, but `encoding` is missing)
      required:
      (...omitted)
      - encoding
```

This manifests on the "Response Schema" of https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content

## Expected

`encoding` to be spec'd
