### ISSUE TITLE
[Schema Inaccuracy / Question] `owner` in `#/components/schemas/repo-search-result-item/` and `#/components/schemas/repository` is nullable

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#440]
# Schema Inaccuracy

**Update**: See [comment below](https://github.com/github/rest-api-description/issues/440#issuecomment-874207987) for `#/components/schemas/repository`

```yml
    repo-search-result-item:
      title: Repo Search Result Item
      description: Repo Search Result Item
      type: object
      properties:
        id:
          type: integer
        node_id:
          type: string
        name:
          type: string
        full_name:
          type: string
        owner:
          nullable: true
          allOf:
          - "$ref": "#/components/schemas/simple-user"
        # ...
```

## Expected

I didn't expect it to be nullable. If it is for a good reason, can we add add a description explaining what the reason is?

ref https://github.com/octokit/types.ts/issues/338

**Comment by creativecreatorormaybenot** [comment]
To add to that, this must have been changed in the last few days. I sadly cannot figure out in which commit since the Git diff (on GitHub) does not seem to work properly with these raw files (and blame does not work at all).

**Comment by gr2m** [comment]
The same problem exists in `#/components/schemas/repository` which is much worse because it is used much more widely

```yml
    repository:
      title: Repository
      description: A git repository
      type: object
      properties:
        id:
          description: Unique identifier of the repository
          example: 42
          type: integer
        node_id:
          type: string
          example: MDEwOlJlcG9zaXRvcnkxMjk2MjY5
        # ...
        owner:
          nullable: true
          allOf:
          - "$ref": "#/components/schemas/simple-user"
        # ...
```
