### ISSUE TITLE
[Schema Inaccuracy] `#/components/schemas/installation-token` is should set `permissions` and `repositorySelection` as required

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#442]
# Schema Inaccuracy

both `permissions` and `repositorySelection` are always set when creating an installation access token

```yml
    installation-token:
      title: Installation Token
      description: Authentication token for a GitHub App installed on a user or org.
      type: object
      properties:
        token:
          type: string
        expires_at:
          type: string
        permissions:
          "$ref": "#/components/schemas/app-permissions"
        repository_selection:
          type: string
          enum:
          - all
          - selected
        repositories:
          type: array
          items:
            "$ref": "#/components/schemas/repository"
        single_file:
          type: string
          example: README.md
        has_multiple_single_files:
          type: boolean
          example: true
        single_file_paths:
          type: array
          items:
            type: string
          example:
          - config.yml
          - ".github/issue_TEMPLATE.md"
      required:
      - token
      - expires_at
```

## Expected

```yml
      # ...
      required:
      - token
      - expires_at
      - permissions
      - repositorySelection
```

## Reproduction Steps

```
$ curl -X POST -H"Authorization: bearer eyJhbGci..." https://api.github.com/app/installations/1/access_tokens
```
