### ISSUE TITLE
[Schema Inaccuracy] Several components have `nullable: true`

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#486]
# Schema Inaccuracy

Example: `simple-user` component

```yml
    simple-user:
      title: Simple User
      description: Simple User
      type: object
      properties:
        name:
          nullable: true
          type: string
        email:
          nullable: true
          type: string
        # ...
      required:
      - avatar_url
      - events_url
      # ...
      nullable: true
```

This is a follow up / related to https://github.com/github/rest-api-description/issues/440

## Expected

I don't think any component should have `nullable: true`.

In the particular case with `simple-user`, it causes the response schema for `GET /installation/repositories` to have the `owner` property be nullable in the repositories array.

This is blocking https://github.com/octokit/openapi-types.ts/issues/136, https://github.com/octokit/app.js/pull/267 and https://github.com/octokit/octokit.js/pull/2123

## Reproduction Steps

not applicable
