### ISSUE TITLE
[Schema Inaccuracy/Question] Can `owner` be null in `repo-search-result-item` component

### ISSUE THREAD

**Issue by gr2m** [github/rest-api-description#549]
# Schema Inaccuracy

```yml
    repo-search-result-item:
      title: Repo Search Result Item
      description: Repo Search Result Item
      type: object
      properties:
        id:
          type: integer
        node_id:
          type: string
        # ...
        owner:
          "$ref": "#/components/schemas/nullable-simple-user"
```

## Expected

See https://github.com/octokit/types.ts/issues/338#issuecomment-918706205. We'd expect that `owner` cannot be set to null. And if it can, could you describe the use case in the property description?

## Reproduction Steps

n/a
