### ISSUE TITLE
[Schema Inaccuracy] Object properties are mistakenly under an array schema

### ISSUE THREAD

**Issue by mattpolzin** [github/rest-api-description#69]
# Schema Inaccuracy

Under the components object, at `schemas/feed/properties/_links`, the `_links` schema is of type `array` but it contains a `required` properties array. Upon inspection, it appears the `required` array should just be nested one level deeper inside the `_links/items` property which is indeed an object and does indeed have properties corresponding to the entries in the `required` array.

## Expected

```yaml
    ...
        _links:
          type: array
          items:
            type: object
            required: # <- the bit that is incorrectly specified directly under `_links` currently.
            - timeline
            - user
            properties:
              timeline:
                type: object
                properties:
                  href:
                    type: string
                  type:
                    type: string
              user:
                type: object
                properties:
                  href:
                    type: string
                  type:
                    type: string
    ...
```
