### ISSUE TITLE
[Schema Inaccuracy]  Add `format: int64` to organization `private_repos`

### ISSUE THREAD

**Issue by rgmz** [github/rest-api-description#707]
# Schema Inaccuracy

The `organization-full` -> `plan`  -> `private_repos` key is defined as `type: integer`, which is interpreted by many codegen tools as `int32`. However, if you have an enterprise plan (or at least in our case) the # of private repos returned from the API is `999999999999`, which causes a runtime error.

```
 com.fasterxml.jackson.databind.JsonMappingException: Numeric value (999999999999) out of range of int (-2147483648 - 2147483647)
```

**Schema**
```
 organization-full:
      title: Organization Full
      description: Organization Full
      type: object
      properties:
        plan:
          type: object
          properties:
            private_repos:
              type: integer
```

## Expected

The schema includes a [`format: int64` type definition] https://swagger.io/docs/specification/data-models/data-types/#numbers).

## Reproduction Steps

From an Enterprise plan on GitHub Enterprise Server 3.1.12:

```sh
$ curl --request GET \
  --url https://gh-enterprise.com/api/v3/orgs/ORG_NAME \
  --header 'Accept: application/vnd.github.v3+json'

{
 // other properties
  "plan": {
    "name": "enterprise",
    "space": 123456789,
    "private_repos": 999999999999,
    "filled_seats": 18,
    "seats": 0
  }
}
```

**Comment by nickfloyd** [comment]
Please let us know if this work is still needed.  We're trying to follow up on any older issues to make sure they get properly routed.

**Comment by rgmz** [comment]
Hi @nickfloyd, we are now on [GHES 3.14.x](https://github.com/github/rest-api-description/blob/main/descriptions/ghes-3.14/ghes-3.14.yaml) and this still appears to be an issue.

- `private_repos` still returns `999999999999` (larger than int32)
- `organization-full` still uses `type: integer`, which is generated as an `int32`-equivalent type in a couple of the OpenAPI codegen tools tested.
    ```yaml
      organization-full:
          title: Organization Full
          description: Organization Full
          type: object
          properties:
            ...
            plan:
              type: object
              properties:
                name:
                  type: string
                space:
                  type: integer
                private_repos:
                  type: integer
            ...
    ```
